version: '3.1'

services:
  pdc-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pdctest
      POSTGRES_USER: pdc
      POSTGRES_DB: pdcDB
    ports:
      - 5432:5432