version: '3.1'

services:
  
  pdc-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pdctest
      POSTGRES_USER: pdc
      POSTGRES_DB: pdcDB
      PGDATA: db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pdc-cashbox-service:
    image: cwiegleb/pdc-cashbox-service:no-article
    ports: 
      - 9002:9002
    links:
      - pdc-db:postgresContainer
    environment:
      DB_DRIVER: postgres
      DB_CONNECTION: host=postgresContainer user=pdc dbname=pdcDB sslmode=disable password=pdctest

  pdc-dealer-service:
    image: cwiegleb/pdc-dealer-service:no-article
    ports: 
      - 9003:9003
    links:
      - pdc-db:postgresContainer
    environment:
      DB_DRIVER: postgres
      DB_CONNECTION: host=postgresContainer user=pdc dbname=pdcDB sslmode=disable password=pdctest

  pdc-order-service:
    image: cwiegleb/pdc-order-service:no-article
    ports: 
      - 9004:9004
    links:
      - pdc-db:postgresContainer
    environment:  
      DB_DRIVER: postgres
      DB_CONNECTION: host=postgresContainer user=pdc dbname=pdcDB sslmode=disable password=pdctest
  
  pdc-csv-upload-service:
    image: cwiegleb/pdc-csv-upload-service:no-article
    ports: 
      - 9005:9005
    links:
      - pdc-db:postgresContainer
    environment:
      DB_DRIVER: postgres
      DB_CONNECTION: host=postgresContainer user=pdc dbname=pdcDB sslmode=disable password=pdctest

  pdc-frontend:
    image: cwiegleb/pdc-frontend:no-article
    ports: 
      - 80:80

volumes:  
  db-data:
    driver: local